#+title: 对于如何提问的思考
#+date: 2023-04-30T15:05:15+08:00
#+draft: false
#+tags[]: 提问 ysyx

#+begin_quote
这篇文章是[[https://ysyx.oscc.cc/][一生一芯]]预学习阶段中[[https://ysyx.oscc.cc/docs/prestudy/0.1.html][如何科学地提问]]800字读后感的作业。
#+end_quote

在几年前知道《[[http://www.catb.org/~esr/faqs/smart-questions.html][提问的智慧]]》这篇文章，也随意浏览过一下，今天把文章完完整整地看了一遍，发现还是有一些收获的（看的是英文版，再差也收获了些词汇哈哈）。对于文章的部分总结可以在《[[https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways/blob/master/README.md][别像弱智一样提问]]》里找到(当然这篇文章还包括了其他内容)，而我准备说说我对于“好的提问”以及“通过STFW和RTFM独立解决问题”的一些心得：

* 好的提问
一个好的提问由以下部分组成(选了一些我认为相对重要的部分或者相对容易出现的错误，如果要看全部错误可以阅读原文):
** 提问之前
*** 是否尝试过自己解决问题
   包括是否尝试过通过阅读源代码的方式解决问题（如果具备所需要的能力)
*** 是否做过足够的搜索工作
包括:
   1. 阅读项目官方文档
   2. 项目内部的issue或者discussion搜索（或者是论坛以及mail list等搜索）
   3. Google 搜索
   4. 向chatgpt询问
   5. 是否向一个具有经验的朋友提问
** 提问问题优化
*** 避免 =xy problem=
   什么是 =xy problem= 呢? 简单来说就是 提问者想要解决 *原问题X* ,且觉得解决了 *引申问题Y* 就能解决 X 问题。\\
   这种问题暗示了提问者不仅仅不了解原问题X,而且还不了解他主观判断能够解决原问题的引申问题Y。在这种情况下，这种先入为主的判断很容易对回答者产生影响，而且会将这个问题本身变的复杂化。如果想要了解这两个问题的关联性，直接问这两个问题是否相关，或者有什么关联。但对于单纯想要解决问题X而言，问这种问题就显得不合时宜。
*** 描述问题全面并且列出你的努力
** 问题解决之后
*** 是否需要说谢谢
为什么这个点值得讨论呢？因为在黑客社区中，黑客对于问题本质的关注大于对于礼貌理解的关注。在某些人看来，在一个得到解决的问题的结尾加上”谢谢“是对于他人时间的浪费，让他人点开这个thread去看你的消息，结果只是看到了一句”谢谢“(对于一些不支持快捷查看发了什么消息的网络论坛或者社区来说)。 但在《提问的智慧》作者看来，礼貌并没有害处，有时候还会有帮助。比如他就建议在一个问题得到解决的时候加上谢谢之类的话，还要提到所有对解决这个问题做出贡献的人。因为这样能给人一种完成感，有利于社区的健康发展(缓解黑客的精神疲劳 :))。
*** 给问题添上“解决”的标签并最好能够总结
总结一个问题能帮助后来者更好的解决问题。

* 通过STFW和RTFM独立解决问题
所谓STFW和RTFM就是“search the fucking web”以及“read the fucking manual”。想要深入了解这两个词（比如历史）可以 STFW :)。

我觉得这两点没什么可以争辩的，自己平时也是这么做的。但我觉得心情好的时候“尽管对那些懒虫抱怨一声 RTFM 是正当的，但能给出文档的链接（即使只是建议个 Google 搜索关键词）会更好。”。
