#+title: Switch to Wayland
#+date:  <2022-12-22 Thu>
#+draft: false
#+tags[]: wayland rice
Switch to Wayland

* Installation
I choose [[https://github.com/hyprwm/Hyprland][hyprland]] as my Wayland window manager(and compositor) which is based on =wlroots=, it is a really new compositor with a lot of great features, and also it is pretty stable(according to the office). Here is the /stars over time/ charts for it:

#+caption: Hyprland Stars Over Time
[[https://starchart.cc/hyprwm/Hyprland.svg]]

#+begin_src bash
# glfw-wayland is conflict with glfw-x11
paru -S hyprland-git xorg-xwayland xorg-xlsclients qt5-wayland glfw-wayland qt6-wayland
paru -S dunst wireplumber pipewire polkit-kde-agent xdg-desktop-portal-hyprland-git # must-have (from hyprland-wiki)

paru -S wev # xev
paru -S wl-clipboard # xclip
paru -S wtype # xdotool
#+end_src
** applications
#+begin_src bash
paru -S hyprpaper # wallpaper manager under hyprland
paru -S rofi-lbonn-wayland-git # rofi under Wayland
paru -S waybar-hyprland-git # waybar hyprland (enhanced?)
paru -S hyprpick # color picker
paru -S grim slurp swappy # screenshot (swappy is a GUI annotation client for grim+slurp combination, which is enough for screenshot)
paru -S gammastep # screen gamma, alternative for redshift
#+end_src

* Emacs Under Wayland
Please use Emacs with =pgtk= (pure GTK) build to support Wayland. The 29 version of Emacs officially support build with =pgtk= flag=. You can simply get it from AUR:
#+begin_src Bash
paru -S emacs29-git
#+end_src

* Customization
1. cursor:
   1. https://wiki.hyprland.org/FAQ/index.html#how-do-i-change-me-mouse-cursor
   2. https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

* Problems
1. =nm-applet= not appears on Waybar tray (at least for me), so I use =nmtui= in terminal to manage my network connection instead.
2. =megasync= not working properly
3. =jetbrains-toolbox= not appears on the Waybar tray.

* Links:
** Applications
1. https://arewewaylandyet.com/
2. https://wiki.hyprland.org/Useful-Utilities/
3. https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway
** Guides
1. [[https://www.fosskers.ca/en/blog/wayland][Full Wayland Setup on Arch Linux]]
